name: sitkpy_dev

channels:
  - defaults
  - simpleitk
  
dependencies:
  - python=3.9
  - jupyter
  - matplotlib
  - ipywidgets
  - numpy
  - scipy
  - pandas
  - multiprocess
  - SimpleITK>=2.2.0
  - pytest
  - markdown
  - lxml
  - pip
  - pip:
    - black[jupyter]
    - pyenchant
    - itkwidgets[notebook]
    
