name: sitkpy

channels:
  - defaults
  - simpleitk
  
dependencies:
  - python=3.9
  - jupyter
  - matplotlib
  - ipywidgets
  - numpy
  - scipy
  - pandas
  - multiprocess
  - SimpleITK>=2.2.0
  - pip
  - pip:
    - itkwidgets
    
