name: Linux and OSX Notebook Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  # run testing on the first of each month 5am ET / 9am UTC 
  - cron: '0 9 1 * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install and run black for notebooks
      run: |
        python -m pip install --upgrade pip
        python -m pip install black[jupyter]
        black --check --diff --verbose .
  test:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          data
        key: notebook-data-{{ checksum "data/manifest.json" }}
        restore-keys: |
          notebook-data-{{ checksum "data/manifest.json" }}
          notebook-data-
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install enchant on non windows systems
      shell: bash
      run: |
        if [ "$RUNNER_OS" != "Windows" ]; then
          sudo apt-get update
          sudo apt-get install enchant
        fi
    # pyenchant on windows includes enchant
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r tests/requirements_testing.txt
        jupyter nbextension enable --py --sys-prefix widgetsnbextension
    - name: run the test
      env: 
        SIMPLE_ITK_MEMORY_CONSTRAINED_ENVIRONMENT: 1
      run: |
        pytest -v --tb=short tests/test_notebooks.py::Test_notebooks::test_python_notebook
